### PR TITLE
Fix to handle Google responses containing null

### PR DESCRIPTION
**Pull request by teamsteamdev**
For issue #11:
Fix bug causing `BAD_NETWORK` error on every request
Fix bug causing `null` to be appended to some words
Tweak to pass checks

### CODE REVIEW

**Comment by teamsteamdev** [comment]
Sorry, kinda messy pull request. I'm new to Git.

**Comment by teamsteamdev** [comment]
@JukeboxRhino I made you the commit author.

**Comment by johnsmith0209** [comment]
I run into the same situation and this PR seems to fix it. Wish this PR to be merged soon. Thank you all. @teamsteamdev @matheuss

**Comment by StephanBijzitter** [comment]
@matheuss Can this please be merged?

**Comment by arthurlacoste** [comment]
@StephanBijzitter This is a good idea !!!

**Comment by scottie** [comment]
when will this me merged to NPM ??

**Comment by JukeboxRhino** [comment]
Alright everybody, I've created a new npm package titled `google-translate-api-extended` and I'm hosting the git fork here https://github.com/JukeboxRhino/google-translate-api.

Please, feel free to submit pull requests as I'm active enough on git to get them handled in a much timelier manner than this repo.

Cheers to continued development!

@teamsteamdev @StephanBijzitter @scottie @arthurlacoste @snkrsnkampa

**Comment by teamsteamdev** [comment]
@JukeboxRhino Thanks for taking this on! I'd love to open an issue for discussion over on your fork, but there's no issues tab. Should I just make a PR?

**Comment by matheuss** [comment]
@JukeboxRhino @teamsteamdev unfortunately I have no time to work on this module anymore :( I'd love to add someone as a maintainer – would you be up to it @JukeboxRhino?

**Comment by JukeboxRhino** [comment]
Sure, go ahead and add me

**Comment by matheuss** [comment]
Done @JukeboxRhino 🙌 Please hit me up at matheus@zeit.co for anything else – e.g. when it's ready to ship, I'll give you access to npm etc 👌

**Pull request closed without merging**
