### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by JukeboxRhino**
Fix bug causing BAD_NETWORK error on every request

### CODE REVIEW

**Comment by dragonfire535** [comment]
While you're at it you might as well change all of the `undefined` and `true` checks to use the same method. It doesn't make much sense to check for one specifically.

**Comment by tgyou** [comment]
I am having a problem today too. The problem is that it returns 'null' instead of 'undefined'.
https://github.com/tgyou/google-translate-api/commit/89c3b1f470eee0fcd7b6089d113da7bbf71fca22

**Comment by dragonfire535** [comment]
Exactly, that's why I'm saying you should change all the undefined checks.

**Comment by teamsteamdev** [comment]
@JukeboxRhino: Ok, I'm new at this. ¯\\_(ツ)_/¯

I made the changes @dragonfire535 suggested and tweaked it to pass the checks. I made a pull request of my own, but I'm thinking _you_ figured this out. Should I:

- make a pull request to your fork and close my pull request, or just
- rebase to make you the author of the commit in my fork?

**Comment by JukeboxRhino** [comment]
@teamsteamdev Either one is fine, whatever works for you

**Comment by SkeLLLa** [comment]
@JukeboxRhino 
This PR will not actually fix the bug, because google changed response format:

```
0 "[["Hallo Welt","Hello World",null,null,1]]"
1 "null"
2 ""en""
3 "null"
4 "null"
5 "[["Hello World",null,[null],[null],"Hello World",0,0]]"
6 "0.7099877"
7 "null"
8 "[["en"],null,[0.7099877],["en"]]"
9 "null"
10 "null"
11 "null"
12 "null"
13 "null"
14 "[["World"]]"
```

**Comment by JukeboxRhino** [comment]
It's working for me, my chat bot is currently running it. It shows up as
actual `null` in node.js, not the string null

**Comment by SkeLLLa** [comment]
@JukeboxRhino That's an output from `JSON.stringify` so it's ok. The other thing is that it's working not as expected and described in readme, because the field `body[7][0]` now has different index and different format.

**Comment by JukeboxRhino** [comment]
Someone merged a different pull request with the same fix, closing

**Pull request closed without merging**
